# Example configuration for MeshBBS
# Copy this to config.toml and customize for your setup

[bbs]
name = "MeshBBS Station"
sysop = "sysop"
location = "Los Angeles"
zipcode = "90210"
description = "Describe what your BBS is for here in one line"
max_users = 100
session_timeout = 10 # minutes of inactivity before automatic logout
welcome_message = "Welcome to this Mesh BBS"

[meshtastic]
# Serial port for Meshtastic device (Linux/macOS: /dev/ttyUSB0, Windows: COM3)
port = "/dev/ttyUSB0"
baud_rate = 115200
# Your Meshtastic node ID (will be auto-detected if not specified)
node_id = ""
# Channel to monitor (0 = primary channel)
channel = 0

[storage]
# Directory to store BBS data
data_dir = "./data"
# Maximum size for a single message (bytes)
# Maximum payload allowed by Meshtastic practical text frame size is 230 bytes.
# Values above 230 will be clamped internally.
max_message_size = 230
# How long to keep messages (days)
message_retention_days = 30
# Maximum number of messages per area
max_messages_per_area = 1000

[message_areas]
# Define message areas/forums
[message_areas.general]
name = "General Discussion"
description = "General chat and discussion"
read_level = 0
post_level = 0

[message_areas.technical]
name = "Technical Support"
description = "Technical help and support"
read_level = 0
post_level = 0

[message_areas.announcements]
name = "Announcements"
description = "Important announcements"
read_level = 0
post_level = 10  # Higher level required to post

[logging]
level = "info"
# Log file path (optional)
file = "meshbbs.log"