# Example configuration for MeshBBS
# Copy this to config.toml and customize for your setup

[bbs]
name = "MeshBBS Station"
sysop = "sysop"
location = "Los Angeles"
description = "Describe what your BBS is for here in one line"
max_users = 100
session_timeout = 10 # minutes of inactivity before automatic logout
welcome_message = "Welcome to this Mesh BBS"

[meshtastic]
# Serial port for Meshtastic device (Linux/macOS: /dev/ttyUSB0, Windows: COM3)
port = "/dev/ttyUSB0"
baud_rate = 115200
# Your Meshtastic node ID (will be auto-detected if not specified)
node_id = ""
# Channel to monitor (0 = primary channel)
channel = 0

[storage]
# Directory to store BBS data
data_dir = "./data"
# Maximum size for a single message (bytes)
# Maximum payload allowed by Meshtastic practical text frame size is 230 bytes.
# Values above 230 will be clamped internally.
max_message_size = 230

[message_topics.general]
name = "General"
description = "General discussions"
read_level = 0
post_level = 0

[message_topics.community]
name = "Community"
description = "Events, meet-ups, and community discussions"
read_level = 0
post_level = 0

[message_topics.technical]
name = "Technical"
description = "Tech, hardware, and administrative discussions"
read_level = 0
post_level = 0

[logging]
level = "info"
# Log file path (optional)
file = "meshbbs.log"
# Security log file (optional)
security_file = "meshbbs-security.log"

[security]
# Optional Argon2 password hashing parameters
# [security.argon2]
# memory_kib = 19456
# time_cost = 2
# parallelism = 1